### ISSUE TITLE
Speeches aren't working

### ISSUE THREAD

**Issue by beren12** [leonardopsantos/LunarSphere#1]
I miss my witty rez speeches. I have way to many to use a macro. This add-on kinda does it maybe it'll help to see how they do it:
https://www.curseforge.com/wow/addons/thaliz-rez-dem-deads

**Comment by beren12** [comment]
Any possibility for an update? will be really useful for picking the right mount in tbc.

**Comment by leonardopsantos** [comment]
Hi! Sorry for the (very) late reply! Sure, I'll give it a go at fixing the speeches.

**Comment by beren12** [comment]
No worries, it still doesn't work :-) 

This add-on has speech working, hopefully we can get it working with just 'say' and not require to be in group.

**Comment by beren12** [comment]
Any chance to look at speech yet?

**Comment by leonardopsantos** [comment]
Oh, sorry, I thought that this was solved.

I'll take a look at it this week.

I don't remember how to enable speechs, can you help me out with that?

**Comment by leonardopsantos** [comment]
I've enabled speeches for the mount and rez on my shaman, I think they're working as expected on LS 1.18.
