### ISSUE TITLE
Can't create buttons for the different types of Polymorph spells (WotLK)

### ISSUE THREAD

**Issue by leonardopsantos** [leonardopsantos/LunarSphere#12]
From

https://www.curseforge.com/wow/addons/lunarsphere-fan-update?comment=347

> Is there any way to set up a menu of the polymorph variants?  I find no matter what I do, I get all sheep, turtles or pigs, but I can't stock a menu with one of each.  Any thoughts?  And thanks again

**Comment by leonardopsantos** [comment]
Assuming this is in the WotLK client, no, there isn't because of the way LS and the game handle casting spells and spell ranks. The different Polymorph spells are considered ranks. Try the following macro:

```
/cast Polymorph
```

That will cast the highest polymorph spell, which for my mage is the pig one. 

## Workaround

Use a macro to force LS to cast a spell with a given rank:

```
/cast Polymorph(rank 4)
```

The variants are:

* `/cast Polymorph(rank 4)`
* `/cast Polymorph(Turtle)`
* `/cast Polymorph(Serpent)`
* `/cast Polymorph(Black Cat)`
* `/cast Polymorph(Pig)`

For a fun button, put the following macro in a button to use a random flavour of Polymorph

```
/castrandom Polymorph(rank 4),Polymorph(Turtle),Polymorph(Serpent),Polymorph(Black Cat)
```

See [`castrandom`](https://wowpedia.fandom.com/wiki/MACRO_castrandom)

**Comment by Velarax** [comment]
Thank you so much for taking the time to explain this.  It works!
