### ISSUE TITLE
Healthstones not detected correctly

### ISSUE THREAD

**Issue by beren12** [leonardopsantos/LunarSphere#2]
I'm leveling a lock and use highest healthstone and use highest healing item doesn't know about just plain 'healthstone' it tells me out of stock.

**Comment by leonardopsantos** [comment]
Do you mind testing this again with the latest version (1.50)? I tested this on the Retail and BCC clients and setting a button to either "Use strongest healing item" or "Use strongest healthstone" did use a healthstone.

- Which client is this?
- How do you reproduce the error?
- Is there a Lua error?

**Comment by beren12** [comment]
This is the TBC Classic client, I made a hearthstone on my warlock and for both "strongest healing item" and "strongest healthstone" it tells me the item is out of stock. I have no health pots on me, but I do have 2 points in improved healthstones. No lua errors for LS.

**Comment by beren12** [comment]
Im pleased to say use random mount works now!

**Comment by leonardopsantos** [comment]
> This is the TBC Classic client, I made a hearthstone on my warlock and for both "strongest healing item" and "strongest healthstone" it tells me the item is out of stock. I have no health pots on me, but I do have 2 points in improved healthstones. No lua errors for LS.

OK, thanks for that info. Maybe the HS are correctly detected, but not the improved ones. I'll take a look as soon as I can.

As a workaround, can you use the imp HS as regular items?

**Comment by beren12** [comment]
> On May 31, 2021, at 11:44 AM, Leonardo Pereira Santos ***@***.***> wrote:
> 
> 
> This is the TBC Classic client, I made a hearthstone on my warlock and for both "strongest healing item" and "strongest healthstone" it tells me the item is out of stock. I have no health pots on me, but I do have 2 points in improved healthstones. No lua errors for LS.
> 
> OK, thanks for that info. Maybe the HS are correctly detected, but not the improved ones. I'll take a look as soon as I can.
> 
> As a workaround, can you use the imp HS as regular items?

Yeah but doesn’t help if someone gives you a different grade/talent healthstone :-) each healthstone has 3 versions depending on the talents.

**Comment by leonardopsantos** [comment]
Can you try version 1.51? It should be fixed there.

**Comment by leonardopsantos** [comment]
Should be fixed on 1.51.

**Comment by leonardopsantos** [comment]
Fixe don version 1.51
