### ISSUE TITLE
Mage template not working

### ISSUE THREAD

**Issue by ballinoutactrl** [leonardopsantos/LunarSphere#3]
When you choose the mage template the buttons do not show up at all around the health and mana circles

**Comment by ballinoutactrl** [comment]
This issue is on the burning crusade classic

**Comment by leonardopsantos** [comment]
I just tested this issue on LS 1.58 by creating a new Mage character and it's working fine.

<img width="550" alt="Untitled" src="https://user-images.githubusercontent.com/9758700/162635498-512225f6-0469-4fdb-9631-2f8ec7fe6699.png">

Can you still reproduce this error on LS 1.58?

**Comment by ballinoutactrl** [comment]
This was fixed a while ago. Everything seems to be working
