### ISSUE TITLE
Spell mounts aren't working for Classic/BCC

### ISSUE THREAD

**Issue by beren12** [leonardopsantos/LunarSphere#4]
Things like the white ram, paladin charger, etc.

**Comment by leonardopsantos** [comment]
Yeah, that's a work in progress. I have something that I thought was working, but BCC broke it.

**Comment by leonardopsantos** [comment]
Can you try version 1.51? It should be fixed there.

**Comment by leonardopsantos** [comment]
Considering fixed.
