### ISSUE TITLE
prevent SAY from throwing error outside of instances

### ISSUE THREAD

**Issue by speedwaystar** [leonardopsantos/LunarSphere#6]
moduleSpeech.lua, line 1089:

`							if ( (forceChannel or channel) ~= "SAY" ) or IsInInstance() then
								SendChatMessage(speechLine, forceChannel or (channel));
							end
`

**Comment by leonardopsantos** [comment]
I'll give these a try. Thanks!

**Comment by leonardopsantos** [comment]
Closing this issue as the patch was applied.
