### ISSUE TITLE
Please host on curse alternative

### ISSUE THREAD

**Issue by beren12** [leonardopsantos/LunarSphere#8]
Overwolf has decided against issuing API keys to wowup and others, so please upload to wago.io or even just tag and cut releases here and msg wowup to get added to the wowup hub: https://wowup.io/guide/wowup/hub

**Comment by leonardopsantos** [comment]
Pinged one of the mods, let's see if 1.58 makes it to WowUp.

**Comment by leonardopsantos** [comment]
Done!

https://wowup.io/addons/1414683

Thanks so much for point me to WoWUp.
