### ISSUE TITLE
Wrath updates

### ISSUE THREAD

**Issue by beren12** [leonardopsantos/LunarSphere#9]
Needs a lot of work for wrath, like all the food/mount/water etc buttons dont work anymore, and I never could get speech to work in tbc...

**Comment by leonardopsantos** [comment]
LS 1.60 fixes mount selections. Food and water selection are working for me.

**Comment by leonardopsantos** [comment]
Food, mount, water, and healthstones are working in WotLK as of 1.61. Will open specific issues if something else isn't working. Closing.
